Add explicit dependency on Rust 1.62
This improves the error reporting when the crate is
compiled with older versions of rustc.

Specifically, #1123 tracks instances of Ubuntu rustc
giving obscure errors when users attempt to compile
spotifyd

With this change, this error becomes

> error: package `spotifyd v0.3.3 (...)` cannot be built because it requires rustc 1.62 or newer, while the currently active rustc version is 1.61.0

which is much more helpful to users diagnosinig the issue.